-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM(
    SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
    FROM ANIMAL_INS AS INS
    INNER JOIN ANIMAL_OUTS AS OUTS
        USING(ANIMAL_ID)
    WHERE
        INS.SEX_UPON_INTAKE != OUTS.SEX_UPON_OUTCOME
        AND (OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%')
) AS SPAYED

ORDER BY
    ANIMAL_ID;