# -- 코드를 입력하세요
SELECT NAME, DATETIME
FROM(
    SELECT
        ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
    FROM ANIMAL_INS
    LEFT JOIN ANIMAL_OUTS
        USING (ANIMAL_ID)
    WHERE
        ANIMAL_OUTS.ANIMAL_ID IS NULL
) AS INS2
ORDER BY
    ANIMAL_INS.DATETIME
LIMIT 3;