-- 코드를 입력하세요
SELECT
    AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM
    BOOK
INNER JOIN AUTHOR
    USING (AUTHOR_ID)
INNER JOIN BOOK_SALES
    USING (BOOK_ID)
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID, CATEGORY DESC;
