-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT 
INNER JOIN FOOD_ORDER
    USING(PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID;